### ISSUE TITLE
"Install buildifer" step fails

### ISSUE THREAD

**Issue by ChrisCummins** [FelixSeptem/pre-commit-golang#4]
My CI config recently started failing on 12f5442f51377b10b26651ad745206bbe1500ad6 with:

```
Run go get github.com/bazelbuild/buildtools/buildifier
  go get github.com/bazelbuild/buildtools/buildifier
  buildifier --version
  shell: /usr/bin/bash -e {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.18.0/x6[4](https://github.com/facebookresearch/CompilerGym/runs/5800783725?check_suite_focus=true#step:5:4)
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
Error: Process completed with exit code 1.
```

Usage:

```yaml
    - repo: https://github.com/FelixSeptem/pre-commit-golang
      rev: 12f5442f51377b10b26651ad745206bbe1500ad6
      hooks:
          - id: bazel-buildifier
```
